// 浏览器顶部标签
export default function Head() {
  return (
    <>
      <title>还入一梦中</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/sssh-logo.ico" />
    </>
  )
}
